In [6]:
# -*- coding:utf-8 -*-
import akshare as ak
fund_rating_all_df = ak.fund_rating_all()
print(fund_rating_all_df)
fund_em_open_fund_info_df = ak.fund_em_open_fund_info(fund="001487", indicator="累计净值走势")
print(fund_em_open_fund_info_df)
fund_portfolio_hold_em_df = ak.fund_portfolio_hold_em(code="001487", year="2021")
print(fund_portfolio_hold_em_df)

          代码             简称       基金经理 基金公司 5星评级家数 上海证券 招商证券 济安金信    手续费  \
0     270007       广发大盘成长混合         苗宇   广发      1    4    3    5  0.15%   
1     270009        广发增强债券C      张芊,方抗   广发      0    2    3    2  0.00%   
2     270010  广发沪深300ETF联接A         刘杰   广发      0         4       0.12%   
3     270014          广发货币B        温秀娟   广发      1                 0.00%   
4     270025      广发行业领先混合A         程琨   广发      0    5    3    1  0.15%   
...      ...            ...        ...  ...    ...  ...  ...  ...    ...   
6015  006066      中加颐睿纯债债券A      王霈,于跃   中加      0                 0.08%   
6016  519120    浦银安盛新兴产业混合A         吴勇   浦银      0         4    2  0.15%   
6017  005535       泰信竞争优选混合        徐慕浩   泰信      1                 0.15%   
6018  000911        鑫元合丰纯债A  郑文旭,丁汀,陈浩   鑫元      0         3    4  0.04%   
6019  006337        华安安浦债券A        周舒展   华安      0                 0.08%   

           类型  
0      混合型-偏股  
1     债券型-混合债  
2      指数型-股票  
3         货币型  
4      

In [7]:
hold_em_dic = {}
for fund_id in fund_rating_all_df["代码"]:
    try:
        print(len(hold_em_dic))
        fund_portfolio_hold_em_df = ak.fund_portfolio_hold_em(code=fund_id, year="2021")
        hold_em_dic[fund_id] = fund_portfolio_hold_em_df["股票名称"]
    except:
        continue
print(len(hold_em_dic))

0
1
1
2
2
3
4
5
5
6
6
6
6
6
7
8
9
10
11
12
13
14
14
14
14
14
14
15
16
17
18
19
20
21
21
22
22
23
24
25
26
27
28
29
29
30
30
30
30
31
31
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
54
55
55
56
57
58
59
60
61
61
62
63
64
65
65
66
67
68
69
70
70
70
71
72
72
73
74
75
75
75
76
76
77
78
79
80
80
80
80
80
80
81
81
82
83
84
85
86
86
87
88
88
89
90
91
92
93
94
95
96
97
98
99
100
100
100
101
102
103
104
105
106
107
108
109
110
111
111
111
112
112
112
112
113
114
114
114
115
116
117
118
119
119
119
120
120
120
121
122
123
124
124
125
126
127
128
129
130
131
132
133
134
135
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
151
151
151
151
151
152
153
154
154
154
154
154
155
156
157
158
159
159
159
160
161
161
162
163
163
163
164
165
166
166
167
168
168
168
168
168
169
170
170
171
171
171
172
173
174
174
175
176
176
177
177
177
177
178
179
180
181
182
183
184
185
186
187
187
188
189
190
191
192
193
193
194
195
196
197
198
199
200
200
200
200
200
201
202

1373
1374
1375
1376
1377
1378
1379
1379
1380
1381
1382
1383
1383
1383
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1403
1404
1405
1406
1406
1407
1407
1407
1407
1408
1409
1410
1411
1412
1413
1414
1414
1415
1415
1416
1417
1417
1418
1419
1420
1421
1421
1421
1421
1422
1423
1423
1424
1425
1426
1426
1427
1427
1427
1428
1429
1430
1430
1431
1432
1433
1434
1435
1435
1436
1436
1436
1437
1438
1439
1439
1440
1440
1440
1441
1442
1443
1444
1445
1446
1447
1447
1448
1448
1449
1450
1451
1452
1453
1454
1454
1455
1456
1457
1457
1458
1458
1458
1459
1459
1459
1460
1461
1462
1463
1463
1464
1465
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1476
1477
1478
1479
1480
1481
1482
1482
1483
1484
1484
1485
1486
1487
1488
1489
1489
1489
1490
1491
1491
1491
1492
1493
1494
1495
1495
1495
1496
1497
1498
1498
1499
1500
1501
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1510
1510
1511
1512
1513
1514
1515
1516
1517
1518
1518
1519
1520
1521
1522


2410
2411
2412
2412
2412
2412
2413
2414
2415
2415
2416
2417
2417
2418
2418
2419
2420
2421
2422
2422
2422
2423
2424
2425
2426
2427
2427
2428
2428
2429
2430
2431
2432
2433
2433
2433
2434
2435
2435
2436
2437
2438
2438
2439
2440
2441
2441
2442
2443
2444
2444
2445
2446
2446
2447
2447
2448
2449
2450
2450
2451
2452
2453
2454
2454
2455
2455
2456
2456
2457
2457
2457
2457
2457
2457
2457
2458
2458
2459
2459
2460
2461
2461
2462
2462
2462
2463
2464
2465
2465
2466
2466
2466
2467
2467
2467
2468
2469
2470
2471
2472
2472
2473
2474
2475
2475
2476
2476
2476
2477
2477
2478
2479
2479
2480
2480
2480
2480
2481
2481
2482
2482
2482
2482
2482
2482
2483
2484
2485
2485
2485
2486
2487
2488
2489
2490
2490
2491
2491
2491
2492
2493
2494
2495
2495
2495
2495
2496
2497
2498
2498
2499
2499
2499
2499
2499
2499
2500
2501
2502
2503
2504
2504
2505
2505
2505
2506
2506
2507
2507
2508
2508
2508
2509
2510
2511
2512
2512
2512
2513
2514
2515
2515
2515
2515
2515
2516
2517
2517
2517
2518
2519
2520
2520
2520
2521
2521
2522
2523
2524


3523
3524
3524
3525
3525
3526
3526
3526
3527
3528
3529
3530
3531
3531
3531
3532
3533
3534
3534
3535
3535
3535
3535
3535
3535
3536
3537
3537
3537
3537
3538
3539
3540
3541
3542
3543
3544
3544
3545
3546
3547
3548
3548
3548
3548
3549
3550
3550
3550
3551
3551
3551
3552
3553
3553
3553
3553
3554
3555
3555
3556
3557
3557
3557
3558
3559
3560
3561
3562
3562
3563
3563
3563
3563
3563
3564
3565
3566
3567
3568
3569
3570
3570
3570
3570
3571
3572
3573
3574
3575
3575
3575
3576
3577
3578
3578
3579
3580
3581
3581
3582
3583
3583
3584
3584
3584
3584
3585
3586
3587
3587
3587
3588
3589
3590
3591
3592
3592
3592
3593
3594
3595
3596
3596
3597
3598
3598
3599
3599
3599
3599
3600
3601
3601
3602
3602
3602
3603
3604
3605
3606
3607
3607
3608
3608
3609
3609
3610
3610
3611
3611
3612
3613
3614
3615
3615
3615
3615
3616
3617
3617
3618
3618
3619
3620
3620
3621
3622
3622
3623
3624
3625
3626
3627
3627
3627
3628
3629
3629
3630
3630
3631
3632
3632
3632
3633
3634
3635
3636
3636
3636
3637
3638
3639
3640
3641
3641
3642
3642
3642


In [19]:
#print(hold_em_dic)
from collections import defaultdict
import numpy as np
save_dic = defaultdict(list)
for key, value in hold_em_dic.items():
    for val in value:
        save_dic[key].append(val)
np.save("hold_em_dic.npy", save_dic)
print(save_dic['560006'])

['中远海控', '中环股份', '北方华创', '重庆百货', '新宙邦', '圣邦股份', '药明康德', '同庆楼', '比亚迪', '博腾股份', '中远海控', '埃斯顿', '爱尔眼科', '重庆百货', '迈瑞医疗', '药明康德', '比亚迪', '东方雨虹', '泰格医药', '博腾股份', '航发动力', '北方华创', '福耀玻璃', '中国中免', '紫金矿业', '美的集团', '华友钴业', '中国铝业', '杭叉集团', '隆基股份', '新宙邦', '北方稀土', '通威股份', '联美控股', '重庆百货', '隆基股份', '东方雨虹', '三一重工', '华友钴业', '中远海控', '爱尔眼科', '紫金矿业', '扬农化工', '埃斯顿']


In [20]:
stock = {}
count = 0
for key, value in hold_em_dic.items():
    for val in value:
        if val not in stock:
            stock[val] = count
            count += 1
print(stock)

{'泸州老窖': 0, '贵州茅台': 1, '五粮液': 2, '药明康德': 3, '中国中免': 4, '爱尔眼科': 5, '宁德时代': 6, '比亚迪': 7, '洋河股份': 8, '凯莱英': 9, '迈瑞医疗': 10, '青岛啤酒': 11, '京东方A': 12, '金山办公': 13, '欣旺达': 14, '卓胜微': 15, '汇川技术': 16, '新益昌': 17, '华利集团': 18, '荣盛石化': 19, '重庆啤酒': 20, '千禾味业': 21, '古井贡酒': 22, '盐津铺子': 23, '峨眉山A': 24, '立讯精密': 25, '财富趋势': 26, '爱美客': 27, '上海家化': 28, '奥泰生物': 29, '恒玄科技': 30, '百克生物': 31, '巴比食品': 32, '贝泰妮': 33, '三峡能源': 34, '东威科技': 35, '中伟股份': 36, '美的集团': 37, '德固特': 38, '利元亨': 39, '纵横股份': 40, '三只松鼠': 41, '申菱环境': 42, '有友食品': 43, '深科达': 44, '中红医疗': 45, '英科再生': 46, '漱玉平民': 47, '迅捷兴': 48, '立高食品': 49, '瑞丰银行': 50, '英诺激光': 51, '震裕科技': 52, '联科科技': 53, '可靠股份': 54, '创识科技': 55, '威腾电气': 56, '苏文电能': 57, '三棵树': 58, '格林精密': 59, '华菱线缆': 60, '南极光': 61, '百川畅银': 62, '药易购': 63, '易瑞生物': 64, '税友股份': 65, '欢乐家': 66, '中辰股份': 67, '德才股份': 68, '嘉亨家化': 69, '普联软件': 70, '英力股份': 71, '中金辐照': 72, '恒辉安防': 73, '雷尔伟': 74, '共同药业': 75, '曼卡龙': 76, '冠中生态': 77, '通用电梯': 78, '深水海纳': 79, '新中港': 80, '志特新材': 81, '川网传媒': 82, '博俊科技': 83, '屹通新材': 84, '和辉光电': 

In [21]:
import numpy as np
features = np.zeros((len(hold_em_dic), len(stock)))
name_dic = {}
count = 0
for key, value in hold_em_dic.items():
    name_dic[count] = key
    for val in value:
        features[count][stock[val]] = 1
    count += 1
print(features)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [24]:
n_dic = {}
for i, key in enumerate(fund_rating_all_df["代码"]):
    n_dic[key] = fund_rating_all_df["简称"][i]
print(n_dic)

{'270007': '广发大盘成长混合', '270009': '广发增强债券C', '270010': '广发沪深300ETF联接A', '270014': '广发货币B', '270025': '广发行业领先混合A', '270028': '广发制造业精选混合A', '240011': '华宝大盘精选混合', '620009': '金元顺安丰祥债券', '630002': '华商盛世成长混合', '530002': '建信货币A', '000122': '汇添富实业债债券A', '000213': '泰信鑫益定期开放C', '166904': '民生加银平稳添利债券A', '000311': '景顺长城沪深300指数增强', '206006': '鹏华全球中短债(QDII)人民币A', '206007': '鹏华消费优选混合', '206009': '鹏华新兴产业混合', '410004': '华富收益增强债券A', '217018': '招商安瑞进取债券', '460007': '华泰柏瑞行业领先混合', '001033': '华夏安康债券C', '001057': '华夏理财30天债券A', '001061': '华夏收益债券(QDII)A', '001065': '华夏海外收益债券现汇', '001066': '华夏海外收益债券现钞', '001078': '华夏现金宝货币B', '002021': '华夏回报二号混合', '000005': '嘉实增强信用定期债券', '481006': '工银红利混合', '481012': '工银深证红利ETF联接A', '481017': '工银量化策略混合A', '162204': '泰达宏利行业混合', '000121': '华夏永福混合A', '150015': '银河银富货币B', '160615': '鹏华沪深300指数(LOF)A', '163005': '长信利众债券(LOF)C', '163110': '申万菱信量化小盘股票(LOF)A', '460300': '华泰柏瑞沪深300ETF联接A', '470007': '汇添富上证综合指数', '470010': '汇添富多元收益债券A', '470011': '汇添富多元收益债券C', '470018': '汇添富双利债券A', '470028'

In [33]:
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
from sklearn.cluster import KMeans
y_pred = KMeans(n_clusters=30, random_state=9).fit_predict(features)
cluster = defaultdict(list)
cluster_name = defaultdict(list)
for i, y in enumerate(y_pred):
    cluster_name[y].append(n_dic[name_dic[i]])
    cluster[y].append(name_dic[i])
print(cluster)

defaultdict(<class 'list'>, {5: ['270007', '270025', '270028', '206009', '159906', '159909', '519021', '240022', '163803', '070006', '213002', '690007', '260112', '260115', '270001', '161601', '570005', '000020', '090001', '090015', '090016', '090018', '519678', '519087', '233007', '161616', '690009', '000017', '320012', '270041', '020015', '530005', '000059', '260104', '070022', '160218', '710001', '163809', '160916', '260109', '360016', '161606', '000117', '020010', '000167', '160215', '164205', '360012', '320003', '070018', '240001', '240004', '270050', '160603', '070001', '070002', '160611', '070011', '213003', '519995', '519011', '000526', '000529', '400025', '519677', '519665', '160219', '000550', '162703', '000612', '000362', '000363', '000751', '000215', '160512', '165519', '040015', '519673', '000574', '000727', '001036', '000978', '001030', '000532', '160919', '580001', '000124', '001097', '000985', '000945', '000946', '001040', '519191', '000011', '000595', '260111', '000996

In [34]:
fp = open("cluster_name.csv", "w")
for key, value in cluster_name.items():   
    fp.write(",".join(value) + "\n")
fp.close()

In [35]:
fp = open("cluster.csv", "w")
for key, value in cluster.items():   
    fp.write(",".join(value) + "\n")
fp.close()